FROM python:3.12-alpine

LABEL maintainer="miraclehand@naver.com"

WORKDIR /app

COPY requirements.txt ./
COPY packages /app/packages

# 필요한 패키지를 설치합니다
#RUN apk update && apk add --no-cache g++ make

RUN pip install --no-index --find-links=/app/packages -r requirements.txt
#RUN pip install -r requirements.txt

COPY ./src /app/src
COPY .env ./

#CMD ["pylint", "**/*.py", "python src/main.py"]
CMD ["python", "src/main.py"]
