replicaCount: 1     # 브로커를 1개로 설정

listeners:
  client:
    protocol: PLAINTEXT

volumePermissions:
  enabled: true

kafkaConnect:
  enabled: true      # Kafka Connect 활성화

configurationOverrides:
  "auto.create.topics.enable": "true"  # 토픽 자동 생성 활성화

topics:
  - name: query-business
    partitions: 3
    replicationFactor: 1
  - name: query-business-response
    partitions: 3
    replicationFactor: 1
  - name: query-business-qa # for elasticserach statistics
    partitions: 3
    replicationFactor: 1
