apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: ollama-tinyllama
  ports:
    - port: 11434            # 클러스터 내에서의 서비스 포트
      targetPort: 11434      # Pod 내에서의 포트
