apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-white-paper
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: business-white-paper
  template:
    metadata:
      labels:
        app: business-white-paper
    spec:
      containers:
      - name: business-white-paper-container
        image: localhost:32000/business-white-paper:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: /app/models/bge-m3  # 컨테이너 내 경로
            name: model-volume
          - mountPath: /app/business-data-library/vectorstore  # 컨테이너 내 경로
            name: vectorstore-volume
      volumes:
        - name: model-volume
          hostPath:
            path: /home/ypark/Dev/im-ai-bot/app/business-white-paper/models/bge-m3  # 로컬 파일 경로
        - name: vectorstore-volume
          hostPath:
            path: /home/ypark/Dev/im-ai-bot/app/business-white-paper/data-library/vectorstore
      dnsPolicy: None  # 기본 DNS 정책을 None으로 설정
      dnsConfig:
        options:
        - name: "ndots"
          value: "5"
        nameservers:
          - 10.152.183.10
        searches:
          - default.svc.cluster.local
          - svc.cluster.local
          - cluster.local
          - davolink
