apiVersion: v1
kind: Service
metadata:
  name: business-white-paper-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: business-white-paper
  ports:
    - port: 8080            # 클러스터 내에서의 서비스 포트
      targetPort: 8080      # Pod 내에서의 포트
      nodePort: 31030       # 외부에서 접근할 포트
