apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway-container
        image: localhost:32000/api-gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      dnsPolicy: None  # 기본 DNS 정책을 None으로 설정
      dnsConfig:
        options:
        - name: "ndots"
          value: "5"
        nameservers:
          - 10.152.183.10
        searches:
          - default.svc.cluster.local
          - svc.cluster.local
          - cluster.local
          - davolink

